services:
  front-end:
    container_name: frontend_container_test
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 9091:5000

  backend:
    container_name: backend_container_test
    build: 
      context: ./Backend
      dockerfile: Dockerfile.node
    ports:
      - "9090:9000"
    depends_on:
      - mysql
      - python-gen
      - python-ds
    environment:
      - PORT=9000
      - HOST=mysql
      - USER=root
      - PASSWORD=mySql123
    command: sh -c "sleep 20 && node app.js"
    volumes:
      - shared_temp:/temps
      # - ./Backend/temps:/temps
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    container_name: mysql-container_test
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mySql123
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql-conf.d:/etc/mysql/conf.d
      - sql_volume:/var/lib/mysql
    command: --lower_case_table_names=1

  python-gen:
    image: python-gen-test
    build: 
      context: ./Backend
      dockerfile: Dockerfile.gen
    stdin_open: true
    tty: true

  python-ds:
    image: python-ds-test
    build:
      context: ./Backend
      dockerfile: Dockerfile.ds
    stdin_open: true
    tty: true
    volumes:
      - shared_temp:/temps
      # - ./Backend/temps:/temps

volumes:
  sql_volume:
    driver: local
  shared_temp:
    name: shared_temp
    driver: local