services:
  backend:
    container_name: backend_container
    image: ide-image
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - PORT=9000
      - HOST=localhost
      - USER=root
      - PASSWORD=mySql123
      - DEFAULT_DATABASE=sys

  mysql:
    container_name: mysql-container
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : ${PASSWORD}

volumes:
  sql_volume:
    driver: local